### PR TITLE
Setup Storybook and Loki with Expo/RN

### LINKED ISSUE #2: Add Storybook

### LINKED ISSUE #3: Add loki

### PR DESCRIPTION
**Pull request by blaketarter**
## Description

Initial setup for storybook, currently it runs the UI in the browser and displays the stories on device.

At the moment you should be able to run `npm run start:visual` to start expo with the storybook entry point, navigate to `localhost:7007` in the browser and then load an emulator/simulator to see the Storybook story on device.

The current limitation is that any stories added in a component directory aren't automatically picked up, you have to also import the story file in `src/stories/index.ts`. This is because you can't use `require.resolve` while using the metro bundler.

Loki also works, it assumes that `npm run start:visual` is running and you can start it with `npm run test:visual`. ~Currently it's only setup to run tests on an iOS simulator.~

### How to run

- Ensure that `xCode` is setup and you can start a simulator
- Ensure that `Android Studio` is setup correctly and you can start an android emulator an can use `adb`
- If you are going to use an android emulator it needs to be running at this point
- run `npm run start:visual` to start both expo and storybook
- press `i` in the running expo process to open storybook on the iOS simulator
- press `a` in the running expo process to open storybook on the Android emulator
- make sure that the storybook UI that opened in the web browser shows the list of stories on the left panel
- make sure that storybook actually opened on both devices
- changing a story in the storybook UI should change what story is being shown on all open devices
- run `npm run test:visual` to run loki against both iOS and Android

### What I did

Here's the important bits of what had to be done to setup storybook and loki:
- Install the new dependencies related to storybook and loki
- Add the config needed to get storybook running
    - Everything in `./storybook`
    - New entry point for the storybook on device `./src/index.storybook.tsx`
    - Make sure the `app.json` points to the normal app entry point
    - Add a new `app-storybook.json` that points to the storybook entry point
    - Add the new `./src/stories/index.tsx` file that gathers all of the stories throughout the 
codebase
    - Add the correct scripts to run storybook on device and in the browser
        - `"start:visual:expo": "expo start --config=app-storybook.json --no-dev"` - on device
        - `"start:visual:storybook": "start-storybook"` - in browser
- Add the config to get loki running in the `package.json`
- Add the scripts related to loki (everything that starts with `test:visual`)
- Add the patch to loki using `patch-package` located in `./patches/loki+0.18.1.patch` to fix an issue with this version of loki

### Troubleshooting

- expo needs to be started with some extra flags to ensure it will work with storybook and loki, `npm run start:visual` will start it with these extra flags for you, but any other expo processes need to be stopped
    - `--config=app-storybook.json`  tells it to use the different entry point
    - `--no-dev` is a fix to ensure that expo does not recompile in the middle of the android loki tests
- if adb is not setup correctly or the android emulator is not running when you start the expo process it wont tie the web storybook UI together with the android app correctly

Closes #2 
Closes #3

## 🔎 Reviewer Checklist

> Checked off by the PR **Reviewers**

### Required

> These always need to be checked

- [x] Merge destination is correct
- [ ] Code is correct as understood and conforms to quality standards
- [ ] Tests have been added where appropriate (unit, visual, end-to-end)
- [ ] Acceptance Criteria have been met

### Additional

> Delete if unneeded

- [ ] Code has been tested and confirmed locally

---

>### Roles & Responsibilities
>
>#### 👨‍💻 Assignee
>
>- Initiator of this PR (be sure to set in GitHub UI)
>- Addresses feedback and change requests
>- Merges PR once approved (usually deletes branch unless `develop` or `release`)
>
>#### 👩‍💻 Reviewer
>
>- Invited to review PR by **Assignee** (via GitHub UI)
>- Is expected to complete a review and address followup

### CODE REVIEW

**Review by roblafeve — COMMENTED** [review]
This looks great! I'll let others test this out though 👍

Also, what about Android?

**Comment by luiz-chagas** [comment]
Still reviewing it, I'll follow up on Monday

**Review by luiz-chagas — APPROVED** [review]
Good job, it works pretty well! 👍

**Comment by blaketarter** [comment]
@roblafeve It should be possible to run the stories on android as well, I'll download Android Studio and test it out.

**Comment by blaketarter** [comment]
I re-did the configuration a bit to ensure that both Android and iOS work just fine as well as updated the PR description to add more information. Let me know if everything still works.

**Review by roblafeve — APPROVED** [review]

**Pull request merged**
